### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Heltrato** [versedi/FontsCombinedMonoScripts#1]
Hello i saw this one in a forums and this font style look really amazing, i was wonder how can i setup or install this one? I will share this to my colleagues also thank you

**Comment by versedi** [comment]
If you want to use the FiraCodePacifico screenshot included in README you can download the TTF and set the font in your IDE. 

As for building you need to clone the repo, install dev dependencies, add your combinations to https://github.com/versedi/FontsCombinedMonoScripts/blob/master/fonts-combinations.js and either hardcore the paths inside index.js or adjust the code to load all available inside directory.
